### ISSUE TITLE
Add another thing 

### ISSUE THREAD

**Issue by srich-DWP** [dwp/design-system-community-backlog#10]
<img width="808" alt="screenshot 2019-02-04 at 10 19 53" src="https://user-images.githubusercontent.com/13314733/52202541-aca85900-2866-11e9-8a9d-d15cd5bc43e1.png">

<img width="806" alt="screenshot 2019-02-04 at 10 20 21" src="https://user-images.githubusercontent.com/13314733/52202565-b7fb8480-2866-11e9-88cd-1103f71ca936.png">

<img width="807" alt="screenshot 2019-02-04 at 10 21 00" src="https://user-images.githubusercontent.com/13314733/52202571-c21d8300-2866-11e9-9f96-d5cca33d3a77.png">

**What problem does this design solve?**
This pattern is trying to capture details for multiple things, in this example the need is to capture details of a users job, then ask the user if they have another job. Subsequently it is building a picture of multiple jobs/employment. 
We found replaying  one of the data fields, the most relevant to the theme of the questions (in this example the employer name) helped the user identify which job they were giving information about.
Having a replay of the employer questions they have just answered "You've told us about XXXX" helped the user to separate individual job details
This pattern has been used in a number of question themes within the online form, anywhere where multiple items of a thing need to be captured E.G. Voluntary work, Pensions, Health Insurance.

**Which service are you researching this design on?**
Apply for new style Employment Support Allowance (ESA)

**How have you approached the design?**
We looked at using the 'Add another' pattern, but this wouldn't work for this form as there is a business need to collect data about users employment, such as; employer details, working pattern, any expenses paid and other data attributes. So we needed to have multiple data inputs associated with the job/s and this didn't fit with the existing 'Add another' pattern

**What have you learned from research?**
This pattern has been tested in a lab environment and users found it easy navigate through.  If they had multiple jobs they clearly understood which job they were providing information about.

**Have you tested this for accessibility?**
No accessibility testing has been done yet.

**Comment by HelenOsg** [comment]
New ticket created in backlog
