### ISSUE TITLE
Hint text for text input

### ISSUE THREAD

**Issue by AndyLongDWP** [dwp/design-system-community-backlog#11]
## How have you approached the design?
- have you tried anything that exists already?

## What have you learned from research?
- include any iterations that didn't work.

## Have you tested this for accessibility?
-  if so, what were the findings?

## Link to code
- if you need help publishing your code to the design-examples repo contact Colin Oakley or Craig Abbott.

**Comment by HelenOsg** [comment]
New ticket created in backlog
