### ISSUE TITLE
Header for internal services

### ISSUE THREAD

**Issue by abbott567** [dwp/design-system-community-backlog#15]
## Screenshot

![image](https://user-images.githubusercontent.com/9450064/45744839-5f995280-bbf7-11e8-9ca4-90a8937b6000.png)

## What problem does this design solve?
For internal services, we can't use the GOVUK crown logo.

## Which service are you researching this design on?
- Bereavement
- Move to Universal Credit

## How have you approached the design?
We originally replaced GOV.UK with DWP in the top left, but DWP staff know they work for DWP and a link to DWP's homepage provides no value.

**Comment by HelenOsg** [comment]
New ticket created
