### ISSUE TITLE
Add items to a list

### ISSUE THREAD

**Issue by chrisadesign** [dwp/design-system-community-backlog#19]
## What problem does this design solve?
The user must enter a list of related things, eg previous names

## Version one
![add-item-1](https://user-images.githubusercontent.com/22620603/43396020-18826ebc-93f8-11e8-8288-020a906fa64f.gif)
Version one keeps the user in the same screen and keeps adding more fields as required, and allows the user to remove items on the same screen as well.

## Version two
![add-item-2](https://user-images.githubusercontent.com/22620603/43396022-1b836490-93f8-11e8-8043-df65aa1e9337.gif)
Version two accepts the first entry and then shows a check your answers style screen which allows the user to add more, edit, and delete items, as well as continue the journey.

**Comment by HelenOsg** [comment]
New ticket created in backlog
