### ISSUE TITLE
Confirmation on admin systems

### ISSUE THREAD

**Issue by chrisadesign** [dwp/design-system-community-backlog#35]
There are examples of confirming actions are complete which differ to the standard [confirmation pages](https://www.gov.uk/service-manual/design/confirmation-pages), these seem to be in admin systems (both internal and external) and put the confirmation in a banner at the top of another page.

Example:
![image](https://user-images.githubusercontent.com/22620603/40001554-5cd4787a-5786-11e8-82d3-ce3ccff66ad9.png)

**Comment by HelenOsg** [comment]
Updated ticket
