### ISSUE TITLE
Upload pattern

### ISSUE THREAD

**Issue by yanashmatova** [dwp/design-system-community-backlog#36]
<img width="1031" alt="upload_pattern_no_table" src="https://user-images.githubusercontent.com/38244607/38551367-e4f0e9d2-3cb0-11e8-8723-0a6cf06358b4.png">

![upload_pattern](https://user-images.githubusercontent.com/38244607/38547480-11a8eeca-3ca7-11e8-8456-16d30b0faa64.png)

**_What problem does this design solve?_**
Allows claimants to upload screenshots, photos and scans of documents to the service (to provide proof of their childcare costs in this case).

**_Which service are you researching this design on?_**
Universal Credit

**_How have you approached the design?_**
There was an upload function already in the service that wasn't accessible so I used that as a starting point and improved it.

**_What have you learned from research?_**
Users would choose a file (without pressing 'upload') and would think their file has been uploaded. It took them a few tries to remember to press both buttons. Otherwise they've found the pattern easy to use.

**_Have you tested this for accessibility?_**
It was tested internally and also externally by real JAWS users. It uses the native browser file input, maximising the chances of it working as expected with all assistive technologies. Dragon has a bug where users cannot use file inputs, except in certain versions and only with Firefox. We have added ARIA so that the user is informed about the status of the file, like when the file has finished uploading or there has been a problem. Work on this pattern is not completely finished since submitting the form reloads the page, and we are planning to add the ability to upload over ajax.

**Comment by HelenOsg** [comment]
New ticket created https://github.com/dwp/design-system/issues/432
