### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by abbott567** [dwp/design-system-community-backlog#37]
**_Screenshot_**
![mar-21-2018 23-35-33](https://user-images.githubusercontent.com/9450064/37790701-3008dc7e-2dff-11e8-938a-f15b1c47ad09.gif)

**_What problem does this design solve?_**
There was too much information on one page. Agents needed a way to access the information but didn't necessarily need it all at the same time.

**_Which service are you researching this design on?_**
Bereavement Payment Service

**_How have you approached the design?_**
They were influenced heavily by the tabs on the [GOVUK bank holidays page](https://www.gov.uk/bank-holidays). The main difference being the hover colour; as the contrast ratio on the bank holiday tabs fails WCAG-AA. So for accessibility reasons, I lightened the grey on the hover colour to meet AA.

The tabs have been designed and built with accessibility in mind. The Javascript applies aria-hidden attributes to each content panel to let screen readers know which content is visible. It also adds aria-selected to the active tab.

The tabs work as a progressive enhancement. If Javascript is turned off, all of the content is visible in the page in a linear order, and instead of tabs you just get a list of regular links, which are anchor-linked to the sections using their ids.

**_What have you learned from research?_**
The design started out as multiple pages and links. But agents had issues reorientating themselves when they clicked back and forth as they always ended up at the top of the page once it loaded. The introduction of tabs allowed them to flick between the information quickly without losing their place.

**_Have you tested this for accessibility?_**
Yes. The tabs have been tested by the accessibility compliance team and with assistive tech users. It has been tested using JAWS, Dragon, ZoomText and Read&Write Gold.

**_Link to code_**
https://dwp-design-examples.herokuapp.com/example/tabs

**Comment by HelenOsg** [comment]
https://github.com/alphagov/govuk-design-system-backlog/issues/100

**Comment by jonhurrell** [comment]
Closing this as GDS have updated the tabs component which has addressed the accessibility concerns.
