### ISSUE TITLE
Declaration

### ISSUE THREAD

**Issue by abbott567** [dwp/design-system-community-backlog#38]
<img width="617" alt="screen shot 2018-02-12 at 12 55 27" src="https://user-images.githubusercontent.com/9450064/36097720-08995e62-0ff4-11e8-835b-94be279b046f.png">

**_What problem does this design solve?_**
Adds a breakpoint before submitting that gives the user time to reflect on the information they have entered. Serves any content that the user has to agree to for legal reasons.

**_Which service are you researching this design on?_**
This pattern appears in most DWP citizen-facing services.

**_What have you learned from research?_**
- Despite the content seeming heavy-handed (prosecution etc), most people are fine with submitting truthful data and accept that terms and conditions are commonplace. 

**_Link to code_**
https://dwp-design-examples.herokuapp.com/example/declaration

**Comment by HelenOsg** [comment]
New ticket created
