### ISSUE TITLE
Confirm action

### ISSUE THREAD

**Issue by chrisadesign** [dwp/design-system-community-backlog#39]
**_Screenshot_**
![Shows the service with a draft plan, highlighting the delete link](https://user-images.githubusercontent.com/22620603/36018593-3e144098-0d74-11e8-8a48-30c9059da657.png)
![Shows the alert at the top of the screen once delete is pressed asking the user to confirm they want to delete the draft plan](https://user-images.githubusercontent.com/22620603/36018595-3e2fe85c-0d74-11e8-9d2b-1628afc865a7.png)
![Shows the confirmation message that the plan draft has been deleted](https://user-images.githubusercontent.com/22620603/36018596-3e43a3c4-0d74-11e8-8a43-225db5258ebf.png)

**_What problem does this design solve?_**
Adds an extra step to destructive actions, in this case deleting an item.

**_Which service are you researching this design on?_**
Prepare for Universal Credit

**_How have you approached the design?_**
The design was taken from Notify.

**_What have you learned from research?_**
The content designers on the team are also the users, but they've fed back that they find the red bordered box being the same as an error message box confusing. 

**_Have you tested this for accessibility?_**
The current implementation lacks focus and alert role, this is in dev to fix. 

**_Link to code_**
_Needs doing_

**Comment by HelenOsg** [comment]
new ticket in backlog
