### ISSUE TITLE
Key details bar

### ISSUE THREAD

**Issue by steven-borthwick** [dwp/design-system-community-backlog#41]
## **Searchlight/CIS**

**_Screenshot_**

Expanded
<img width="1167" alt="screen shot 2018-01-10 at 16 56 09" src="https://user-images.githubusercontent.com/12656517/34784823-4b9659f4-f627-11e7-883f-eb5b5bcacc97.png">

Collapsed
<img width="745" alt="screen shot 2018-01-10 at 17 00 06" src="https://user-images.githubusercontent.com/12656517/34785076-fef1496e-f627-11e7-9011-a734d1f2e137.png">

**_What problem does this design solve?_**
The citizen's identity information is visible/available so DWP agents know and are reassured about which record they are viewing. Common info (Name, Date of Birth, NI number, status)

**_Which service are you researching this design on?_**
Searchlight/CIS

**_Notes_**
Has expanded and contracted states when user scrolls but is always visible. 
Has different colour background  (blue = alive, grey = dead or superceded)

**Comment by HelenOsg** [comment]
New ticket created in community backlog
