### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by gunjam** [dwp/design-system-community-backlog#42]
**_Screenshot_**
### Search landing
![screen shot 2017-12-18 at 15 47 39](https://user-images.githubusercontent.com/142065/34114564-0620cb12-e40b-11e7-8a1d-5a69d05b5599.png)
### Search results
![screen shot 2017-12-18 at 15 41 04](https://user-images.githubusercontent.com/142065/34114591-177646b2-e40b-11e7-8364-c46a0bda281e.png)
### Search landing
![screen shot 2017-12-18 at 15 40 13](https://user-images.githubusercontent.com/142065/34114640-3545b696-e40b-11e7-9fc7-85812340bb16.png)
### Search results
![screen shot 2017-12-18 at 15 44 42](https://user-images.githubusercontent.com/142065/34114673-48b9ced8-e40b-11e7-86dd-fb1ab9a82098.png)

**_What problem does this design solve?_**
Searching for things

**_Which service are you researching this design on?_**
Bereavement Support Payment agent facing services

**_How have you approached the design?_**
Stole it from Find pension contact details (screenshots included)

**_What have you learned from research?_**
BSP search results weren't accessible as headings were all the same

**_Have you tested this for accessibility?_**
Yes, with automated tools and real users.

**Comment by HelenOsg** [comment]
New ticket opened
