### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by abbott567** [dwp/design-system-community-backlog#43]
**_Screenshot_**

![pasted_image_at_2017_12_12_05_28_pm_720](https://user-images.githubusercontent.com/9450064/34003517-63c7ed7a-e0ed-11e7-9479-339db738d7de.png)

**_What problem does this design solve?_**
Agent facing systems usually require a navigation bar to link to different features.

**_Which service are you researching this design on?_**
- Bereavement Support Payment

**_How have you approached the design?_**
The design was originally a grey bar with a solid teal background for selected items. The teal was found to fail the colour contrast ratio for WCAG-AA. The teal was then switched to govuk-blue. This tested ok, but then we needed a sub-nav (see screenshot).

The grey bar wouldn't work when embedded halfway down a page, so I looked around for existing designs. The style of nav I have chosen already exists on [companies house](https://beta.companieshouse.gov.uk/search?q=bpdts) and govuk-pay.

**_What have you learned from research?_**
The navigation works fine both as the main nav and the sub-nav. Agents have no issues finding it and using it to navigate the site.

**_Have you tested this for accessibility?_**
This has been tested with the DWP Accessibility Compliance Team and no issues were found. More testing will need to be done with actual users.

**_Link to code_**
- link to follow

**Comment by HelenOsg** [comment]
New ticket created
