### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by abbott567** [dwp/design-system-community-backlog#44]
<img width="415" alt="screenshot-1" src="https://user-images.githubusercontent.com/9450064/33999048-4749044c-e0e1-11e7-97df-9b7d5bd108db.png">

**_What problem does this design solve?_**
Gives people a history of actions. For example, claim history.

**_Which service are you researching this design on?_**
Bereavement Support Payment
Access to work

**_How have you approached the design?_**
I copied the design straight from Access to work. With regards to markup, I changed it to be a list. More work is needed on the markup as it abuses spans.

**_What have you learned from research?_**
We originally just had a list of divs using panel-border-narrow. Each event was a new panel. We have found from research that the timeline version works much better as it's more visually striking. Agents understand immediately what it's for and how to read it.

**_Have you tested this for accessibility?_**
It has been tested by the DWP accessibility compliance team and they found no issues. But more work will need to be done with users, particularly if the markup changes.
 
**_Code_**
https://dwp-design-examples.herokuapp.com/example/timeline

**Comment by HelenOsg** [comment]
New ticket created
