### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by ermlikeyeah** [dwp/design-system-community-backlog#45]
Jobseekers Benefit Enhancement Service agent service

<img width="493" alt="screen shot 2017-12-14 at 10 42 44" src="https://user-images.githubusercontent.com/13417175/33999051-4b53c6da-e0e1-11e7-8d10-89e491a7a9f7.png">
<img width="540" alt="screen shot 2017-12-14 at 10 37 31" src="https://user-images.githubusercontent.com/13417175/33999052-4b6c298c-e0e1-11e7-88b6-dc0f8da26a2c.png">

## How have you approached the design?
- have you tried anything that exists already?

## What have you learned from research?
- include any iterations that didn't work.

## Have you tested this for accessibility?
-  if so, what were the findings?

**Comment by HelenOsg** [comment]
GDS pattern available
