### ISSUE TITLE
Find my address by postcode/house number

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system-community-backlog#52]
## What
Improve the postcode look up as shown in GDS design system ( https://design-system.service.gov.uk/patterns/addresses/)

## Why 
Avoid giving the user a long list of addresses. 

#### Services

- Budgeting loans

**Original issue information** 19 June 2019 @htmlandbacon https://github.com/dwp/design-examples/issues/41

**Comment by jonhurrell** [comment]
Closing this as it's a [duplicate](https://github.com/dwp/design-system/issues/404)
