### ISSUE TITLE
Hint text text inputs

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system-community-backlog#55]
## What
More guidance on the use of hint text in services

## Why
GDS Design system doesn't say whether hint text needs a full stop. See examples on this page with and without one: https://design-system.service.gov.uk/components/error-message/

Use across services is not consistent. We need to make a local ruling on how to punctuate. Options include:

- use full stops in all cases because easier for people using screen readers
- use only for full sentences but not for standalone phrases, eg, 'For example, 31/3/1980'

## Anything else
There are some inconsistencies with how and when/if we use hint text for text inputs across our services. There is also contradictory user research evidence on whether users actually read hint text, depending on the service.

It would be good to find some consistency on when we should use hint text, and if we do, the styles we adopt (full stop at the end, or not, etc.)

UC have agreed guidance but there isn't any agreed guidelines of this.

Update Dec 2020: Roundup of research and current practice by @martinwake : https://github.com/dwp/design-system-community-backlog/discussions/81

**Original issue information:** 24 Jan 2019 @AndyLongDWP  https://github.com/dwp/design-system-community-backlog/issues/11

**Comment by jonhurrell** [comment]
[Published guidance](https://design-system.dwp.gov.uk/components/hint-text). You can contribute research or insights using this [discussion](https://github.com/dwp/design-system-community-backlog/discussions/88).
