### ISSUE TITLE
Header for internal services

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system-community-backlog#58]
## What
A header for internal services

### Example: Move to UC
<img width="774" alt="Screen Shot 2021-03-22 at 08 43 10" src="https://user-images.githubusercontent.com/57486301/111962757-a5964080-8aea-11eb-86fd-ba8130829c7f.png">

## Why
For internal services, we can't use the GOVUK crown logo.

## Anything else
We originally replaced GOV.UK with DWP in the top left, but DWP staff know they work for DWP and a link to DWP's homepage provides no value.

**Original issue information:** 19 September 2018 @abbott567 https://github.com/dwp/design-system-community-backlog/issues/15

**Comment by jonhurrell** [comment]
This has been published on the [design system](https://design-system.dwp.gov.uk/components/internal-header).
If you have any research insights or have used the pattern, let us know on the [GitHub discussion](https://github.com/dwp/design-system-community-backlog/discussions/70).
