### ISSUE TITLE
Cookies policy and consent

### ISSUE THREAD

**Issue by steven-borthwick** [dwp/design-system-community-backlog#6]
## Screenshot

![cookie_consent](https://user-images.githubusercontent.com/12656517/75032943-a866d200-54a1-11ea-9c00-24195eefdf42.png)

## What problem does this design solve?

Help users to understand what cookies do on DWP services and allow them to accept or reject them easily. Allow users to review and update their preferences at any time.

## Which service are you researching this design on?

Apply for Child Maintenance

## How have you approached the design?

Based on GOV.UK guidelines and cookie policy and the NHS consent mechanism.

**Comment by HelenOsg** [comment]
Pattern created and live in design system https://design-system.dwp.gov.uk/patterns/consent-to-cookies
