### ISSUE TITLE
Contact preferences

### ISSUE THREAD

**Issue by jon-houghton** [dwp/design-system-community-backlog#7]
## What problem does this design solve?

Users of DWP services will often need contacting, to notify them of a decision or to update them on progress. How and when we do this should be consistent.

- when and how to contact users
- how to ask users for their preferred contact methods
- how to help users keep their contact details up-to-date

Not everyone has an email address or a mobile phone. Some people can read SMS messages but not take voice calls. Give people choices about how you will contact them. Let your users tell you how, when or why they would like to be contacted by you.

**Let people change their contact preferences**
People’s situation and therefore preferences change over time. Let your users change their contact preferences with you.

## Have you tested this for accessibility?

![Screen Shot 2019-07-25 at 16 04 02](https://user-images.githubusercontent.com/44668996/61885590-f7da2500-aef5-11e9-91af-97c9586b2166.png)

[Contact preferences.pdf](https://github.com/dwp/design-examples/files/3432125/Contact.preferences.pdf)

**Apply for a National Insurance number**
Looking at how to capture contact preferences, alternative phone numbers for SMS and calls and correspondence addresses after we've asked where a person lives earlier in the application.

**Comment by HelenOsg** [comment]
New ticket created in backog
